# Generated by Django 2.0.2 on 2018-03-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPhone', models.IntegerField(max_length=11, unique=True)),
                ('userpasswd', models.CharField(max_length=20)),
                ('userRank', models.CharField(default='黄金会员', max_length=20)),
                ('userBlance', models.IntegerField(default=0, max_length=20)),
                ('userIntegral', models.IntegerField(default=0, max_length=20)),
                ('userCoupon', models.CharField(max_length=150)),
                ('userExpensesRecord', models.CharField(max_length=150)),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
    ]
